ALTER TABLE clients
ADD  CONSTRAINT CHECK_VALID_NAME_SIZE CHECK ( CHAR_LENGTH(name)>=3);

ALTER TABLE planets
ADD  CONSTRAINT CHECK_VALID_NAME_SIZE_OF_PLANET CHECK (CHAR_LENGTH(name)>=1 AND  CHAR_LENGTH(name)<=500)